### ISSUE TITLE
bblayers file is broken

### ISSUE THREAD

**Issue by sakoman** [jhaws1982/meta-batman#1]
I think you want something like this:
# We have a conf and classes directory, add to BBPATH

BBPATH .= ":${LAYERDIR}"
# We have recipes-\* directories, add to BBFILES

BBFILES += "${LAYERDIR}/recipes-_/_.bb \
    ${LAYERDIR}/recipes-_/_.bbappend"

BBFILE_COLLECTIONS += "batman"
BBFILE_PATTERN_batman = "^${LAYERDIR}/"
BBFILE_PRIORITY_batman = "6"

**Comment by jhaws1982** [comment]
You're right - I'll update that right now.
